'use strict';
var ejs = require('ejs');
var fs = require('fs');
var pdf = require('html-pdf');
var moment = require('moment');
var mailing = require('../email.send.service');

exports.mailTemplate  = function (req, res) {
    console.log(req);
    console.log('Inside mail template..');
    var jsonContent = {
        UserName: req.userName,
        LoginId: req.loginId,
        Password: req.password,
        URL: "www.Cutechgroup.com",
        printedOn: moment().format('DD-MMM-YYYY'),
    };

    var options = {};

    options = {
        // Export options 
        "directory": "/tmp", // The directory the file gets written into if not using .toFile(filename, callback). default: '/tmp' 
        // Papersize Options: http://phantomjs.org/api/webpage/property/paper-size.html 
        "format": "A4", // allowed units: A3, A4, A5, Legal, Letter, Tabloid 
        "orientation": "portrait", // portrait or landscape 
        "margin": "0mm",
        "height": "8.3in", // allowed units: mm, cm, in, px 
        "width": "11.7in",
        // Page options 
        "border": "0mm", // default is 0, units: mm, cm, in, px 
        "margin-left": "0mm",
        "margin-right": "0mm",
        "margin-top": "0mm",
        "footer": {
            "height": "15mm",
            "contents": {
                // default: '<table class=\'tdCustom\'  style=\'font-size:8pt;border:0;margin-top:0pt;margin-left:30px;\'><tr><td class=\'tdCustom\'>Generated by cuteTime.</td><td class=\'tdCustom\' style=\'width:90pt; text-align:left\'>Print Date:</td><td class=\'tdCustom\' style=\'width:70pt; text-align:left\'></td><td class=\'tdCustom\' style=\'width:100pt; text-align:left\'>Approved By:</td><td class=\'tdCustom\' style=\'width:70pt; text-align:left\'></td><td class=\'tdCustom\' style=\'width:70pt; text-align:left\'>Approved Date:</td><td class=\'tdCustom\' style=\'width:70pt; text-align:left\'></td><td class=\'tdCustom\' style=\'width:150pt; text-align:right\'>Page {{page}} of {{pages}}</td></tr></table>'
            }
        },
        // Rendering options 
        "base": "file:///home/www/your-asset-path", // Base path that's used to load files (images, css, js) when they aren't referenced using a host 
        // Zooming option, can be used to scale images if `options.type` is not pdf 
        "zoomFactor": "1", // default is 1 
        // File options 
        "type": "pdf"
        //"phantomPath": "file:///D:/Utils/phantomjs-2.1.1-windows/bin/"
    };

    options.header = {
        "height": "25mm"
    };
    fs.readFile('service//email//NewUserEmailTemplate.html', 'utf8', templateResponse);

    // Rendering
    function templateResponse(err, htmldata) {
        console.log('inside template response..');
        if(err){
            console.log(err);
        }
        // console.log(ejs.render(htmldata, jsonContent));
        options.header.contents = ejs.render(htmldata, jsonContent);
        // mailing.sendMail(rendered);
    }
};
